# Generated by Django 5.1.4 on 2025-01-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
